/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedModeratorsIndexRouteImport } from './routes/_authenticated/moderators/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedReportsReportIdIndexRouteImport } from './routes/_authenticated/reports/$reportId/index'
import { Route as AuthenticatedPlansPlanIdIndexRouteImport } from './routes/_authenticated/plans/$planId/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModeratorsIndexRoute =
  AuthenticatedModeratorsIndexRouteImport.update({
    id: '/moderators/',
    path: '/moderators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsReportIdIndexRoute =
  AuthenticatedReportsReportIdIndexRouteImport.update({
    id: '/reports/$reportId/',
    path: '/reports/$reportId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlansPlanIdIndexRoute =
  AuthenticatedPlansPlanIdIndexRouteImport.update({
    id: '/plans/$planId/',
    path: '/plans/$planId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/moderators/': typeof AuthenticatedModeratorsIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/reports/$reportId/': typeof AuthenticatedReportsReportIdIndexRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/moderators': typeof AuthenticatedModeratorsIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdIndexRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/moderators/': typeof AuthenticatedModeratorsIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/_authenticated/reports/$reportId/': typeof AuthenticatedReportsReportIdIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/dashboard/'
    | '/moderators/'
    | '/plans/'
    | '/reports/'
    | '/users/'
    | '/plans/$planId/'
    | '/reports/$reportId/'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/moderators'
    | '/plans'
    | '/reports'
    | '/users'
    | '/plans/$planId'
    | '/reports/$reportId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/moderators/'
    | '/_authenticated/plans/'
    | '/_authenticated/reports/'
    | '/_authenticated/users/'
    | '/_authenticated/plans/$planId/'
    | '/_authenticated/reports/$reportId/'
    | '/_authenticated/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderators/': {
      id: '/_authenticated/moderators/'
      path: '/moderators'
      fullPath: '/moderators/'
      preLoaderRoute: typeof AuthenticatedModeratorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/$reportId/': {
      id: '/_authenticated/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId/'
      preLoaderRoute: typeof AuthenticatedReportsReportIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/$planId/': {
      id: '/_authenticated/plans/$planId/'
      path: '/plans/$planId'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedModeratorsIndexRoute: typeof AuthenticatedModeratorsIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedPlansPlanIdIndexRoute: typeof AuthenticatedPlansPlanIdIndexRoute
  AuthenticatedReportsReportIdIndexRoute: typeof AuthenticatedReportsReportIdIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedModeratorsIndexRoute: AuthenticatedModeratorsIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedPlansPlanIdIndexRoute: AuthenticatedPlansPlanIdIndexRoute,
  AuthenticatedReportsReportIdIndexRoute:
    AuthenticatedReportsReportIdIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
